### ISSUE TITLE
Missing/inaccurate documentation

### ISSUE THREAD

**Issue by Eiim** [Xenira/LiveSplit-Websocket#4]
The endpoint for the server appears to be ws://(local ip):16835/livesplit, however, this is not documented anywhere in the README that I can tell. Additionally, it appears that messages must not end with \r\n, even though this is in the documentation.

It should possibly also be noted that WebSocket Secure is not supported.

**Comment by Xenira** [comment]
Thanks. I honestly never finished this project.

I might not be able to do changes myself atm but contributions would be highly welcome.

**Comment by Eiim** [comment]
Okay, I'll make sure to note any other things I come across and drop them in a PR towards the end if I can reasonably easily fix them.

**Comment by Xenira** [comment]
Thanks alot.
Feel free to create seperate issues for things you find.
I might find some time to add some things myself.
